Feat/58/create class to validate service response
TableRise/tablerise-backend pull request #100
Opened 2023-08-11 23:10 UTC by junglejf

### Technical Checklist

* [ ] Garanti que todos os arquivos criados possuem testes unitários ( quando aplicável ).
* [ ] Garanti que todos os fluxos criados possuem testes de integração.
* [ ] Nenhuma mudança foi feita na estrutura de rotas, ou, se foi feita o arquivo do swagger foi atualizado.
* [ ] A pipeline foi executada com sucesso e a cobertura de testes atingiu ou passou de 90%.
* [ ] Ao finalizar a task movi meu card para a coluna de CodeReview e enviei o link da PR no discord para aprovação.

⚠️ Cuidado com os arquivos e informações sensíveis, nenhuma informação secreta deve ser enviada ao github, tais como:

.npmrc, secrets, senhas, strings de conexão de prod e etc...

### Additional Notes

[ The quality of your code is the resume of your work ]

2023-08-12 05:09 UTC, Adson-Gomes-Oliveira requested changes

2023-08-12 05:09 UTC, Adson-Gomes-Oliveira commented on src/support/helpers/errorMessage.ts
> +    notFound: {
notFoundByID

2023-08-12 05:09 UTC, Adson-Gomes-Oliveira commented on src/support/helpers/errorMessage.ts
> +        system: {
System e default podem ser os mesmos, a implementação é igual o que muda é o nome do paramêtro, mas o tipo é o mesmo. então seria interessante ao unificar esses objetos e trocar o nome do parâmetro por algo mais geral.

2023-08-12 05:39 UTC, Adson-Gomes-Oliveira requested changes

2023-08-12 05:39 UTC, Adson-Gomes-Oliveira commented on src/support/helpers/errorMessage.ts
A ideia é sempre evitar a repetição de código, assim seguindo os conceitos de clean code, porém, algumas vezes,a repetição de pequenas partes de código pode ser aceitável contanto que haja algum ponto positivo nisso.

Quando a complexidade para que não haja repetição aumenta demais esse conceito de clean code pode acabar mais atrapalhando do que ajudando na hora do desenvolvimento, já que um código deve ser acima de tudo, de rápida legibilidade.

No caso do errorMessage realmente as mensagens acabam se repetindo, porém, em alguns momentos a complexidade aumenta demais para evitarmos essa repetição, exemplo:

#### Nos métodos de updateAvailability existe essa validação:
*Com errorMessage:*
`this._validate.active(response.active === query, errorMessage.badRequest.default.responseActive(query));`

Aqui é necessário entender:
- O que é o errorMessage
- Qual o código de erro
- O que é o default e o que é o não default para saber o que utilizar
- O que é o responseActive e porque ele precisa receber essa query

*Sem errorMessage:*
`this._validate.active(response.active === query, ${query ? 'Entity already enabled' : 'Entity already disabled'});`

Aqui é necessário entender:
- O que é a query

Então na minha percepção esse helper ajuda a não repetir texto, não código, afinal o código continua sendo repetido porém não acho que o trade-off de complexidade vale a pena, por exemplo entrar 4 níveis a dentro de um objeto para recuperar uma string que ( em teoria ) nunca irá mudar.

Para legibilidade do código é melhor que a mensagem esteja hard-coded.

@junglejf @RasecMH @ashtrindade

2023-08-12 11:35 UTC, junglejf commented on src/support/helpers/ValidateData.ts
> +    protected validateActive(activeStatus: boolean | undefined | null, errorMessage: string): void {
Sim, quando active for true lança o error, mas a query é o inverso (tecnicamente seria só passar !query e objeto.active). Aí pensei se a função não estaria com responsabilidade dupla? Ela deveria avaliar só objeto.active ou pode ser qualquer tipo de boolean?

Antes eram só as três funções active,entry e response, mas quando entrei no service de system precisei colocar um if e achei melhor separar as funções pra ficar mais parecido como estava no código.

Mas o valdidateExistance fica mais simples no código e pra testar.

2023-08-12 12:56 UTC, junglejf commented on src/support/helpers/errorMessage.ts
Eu tentei manter o padrão de deixar tudo via o helper, mesmo aumentando a complexidade. Se system ficar hardcoded, já tira um nível. Minha sugestão seria simplificar ainda mais.

Poderia ficar ainda mais simples, ao invés de uma mensagem pra cada nome, colocar uma mensagem única. Substiruir
```js
    {
            armor: 'NotFound an armor with provided ID',
            background: 'NotFound a background with provided ID',
            classe: 'NotFound a class with provided ID',
            feat: 'NotFound a feat with provided ID',
            god: 'NotFound a god with provided ID',
            item: 'NotFound an item with provided ID',
            magicItem: 'NotFound a magic item with provided ID',
            monster: 'NotFound a monster with provided ID',
            race: 'NotFound a race with provided ID',
            realm: 'NotFound a realm with provided ID',
            spell: 'NotFound a spell with provided ID',
            system: 'NotFound a system with provided ID',
            weapon: 'NotFound a weapon with provided ID',
            wiki: 'NotFound a wiki with provided ID',
     }  
```     
por
```js
{  notFound an object with providedID } 
```

, porque quando testamos já sabemas se é raça, background, etc. E quando o erro for lançado já é apontado a clase e o arquivo.
        
Esse trecho já acho melhor indicar como conflict(409) ao invés de badequest.

```js
        if (response.active === query) {
            const err = new Error(`${query ? 'Entity already enabled' : 'Entity already disabled'}`);
            err.stack = HttpStatusCode.CONFLICT.toString()  
            err.name = 'BadRequest';

            this._logger('error', err.message);
            throw err;
        }
```

Agora error message ficaria:
  
```js
        export enum ErrorMessage = {
            CONFLICT = ( query ) => (` ${ query ? 'Entity already enabled' : 'Entity already disabled' } )`
            NOT_FOUND =  'notFound an object with providedID' ,
            BAD_REQUEST =  'Not possible to change availability through this route' },
            FORBIDDEN = 'Update the content directly is not allowed',
            UNPROCESSABLE_ENTITY = 'An entity name is required',
            
};
```

2023-08-12 14:09 UTC, junglejf commented on src/support/helpers/ValidateData.ts
> +    protected validateResponse(response: Internacional<any> | any, errorMessage: string): Internacional<any> {
Foi pela saída u mretorna System e o outro Internacional, não tem problema retornar os 2 ?

2023-08-12 14:11 UTC, ashtrindade commented on src/support/helpers/errorMessage.ts
Gostei dessa solução. Elimina um pouco da repetição, mas ainda fica legível.
> Agora error message ficaria:
> 
> ```js
>      export enum ErrorMessage = {
>             CONFLICT = ( query ) => (` ${ query ? 'Entity already enabled' : 'Entity already disabled' } )`
>             NOT_FOUND_BY_ID =  'notFound an object with providedID' ,
>             BAD_REQUEST =  'Not possible to change availability through this route' },
>             FORBIDDEN = 'Update the content directly is not allowed',
>             UNPROCESSABLE_ENTITY = 'An entity name is required',
> };
> ```

2023-08-12 16:09 UTC, RasecMH commented on src/support/helpers/errorMessage.ts
Também gostei da solução com o enum, acredito que continue legível e fácil de entender deixando mais organizado as mensagens.

2023-08-12 17:57 UTC, Adson-Gomes-Oliveira commented on src/support/helpers/ValidateData.ts
> +    protected validateActive(activeStatus: boolean | undefined | null, errorMessage: string): void {
Entendi, o contexto é o seguinte, nos metódos de update o campo active não pode ser enviado no payload e nos métodos de updateAvailability a query não pode ser undefined, os dois casos estão validando a existencia ou não de algo, a responsabilidade é a mesma.

`if (!query && objeto.active) { ... }`

Para essa validação dar certo é necessário que o paramento que recebe o objeto.active tenha valor padrão de **false**

2023-08-12 18:00 UTC, Adson-Gomes-Oliveira commented on src/support/helpers/errorMessage.ts
@junglejf Sensacional mano, ficou elegante o código parabéns. Diminuiu a complexidade da solução sem abrir mão da organização. Top!

2023-08-19 06:50 UTC, junglejf commented on src/support/helpers/errorMessage.ts
> +        system: {
https://github.com/TableRise/tablerise-backend/pull/100/commits/db0a77bd4d1a976425556db0343feec79afc70c9

2023-08-19 14:52 UTC, junglejf commented on src/support/helpers/errorMessage.ts
```js
        export enum ErrorMessage = {
            //CONFLICT = ( query ) => (` ${ query ? 'Entity already enabled' : 'Entity already disabled' } <<< Susbtituído por badreuqest
            NOT_FOUND_BY_ID =  'notFound an object with providedID' ,
            BAD_REQUEST =  'Not possible to change availability through this route' },
            //FORBIDDEN = 'Update the content directly is not allowed',  <<< Substituído por badrequest
            //UNPROCESSABLE_ENTITY = 'An entity name is required', <<< A Mensagem vem do ZodError.msg
            
};
```

```js
        export enum ErrorMessage = {
            NOT_FOUND_BY_ID =  'notFound an object with providedID' ,
            BAD_REQUEST =  'Not possible to change availability through this route' },        
};
```

Fobidden foi simplificado devido a essa alteração:

> O método validateActive retorna erro se for true, esse é o comportamento esperado? Caso não seja:
> 
> * validateActive
> * validateSystemActive
> * validateSystemQuery
> 
> Os três tem a mesma implementação, o que muda é só o código de erro, mas caso uma query não tenha sido enviada faz mais sentido 400 do que 422, uma vez que, se necessário envia-la, não enviar resulta em uma requisição ruim.
> 
> O que acha de transformar esses 3 métodos em apenas um? Assim conseguimos enxugar e simplificar a classe.
> 
> sugestão: validateExistance onde o código de erro será 400 ( BAD_REQUEST )

2023-08-19 17:11 UTC, Adson-Gomes-Oliveira approved these changes

2023-08-19 20:45 UTC, merged