#119 - Create user serializer helper for OAuth API responses
TableRise/tablerise-backend pull request #135
Opened 2023-09-13 14:56 UTC by RafaelCunhaS

### Technical Checklist

* [x] Garanti que todos os arquivos criados possuem testes unitários ( quando aplicável ).
* [x] Garanti que todos os fluxos criados possuem testes de integração.
* [x] Nenhuma mudança foi feita na estrutura de rotas, ou, se foi feita o arquivo do swagger foi atualizado.
* [x] A pipeline foi executada com sucesso e a cobertura de testes atingiu ou passou de 90%.
* [x] Ao finalizar a task movi meu card para a coluna de CodeReview e enviei o link da PR no discord para aprovação.

⚠️ Cuidado com os arquivos e informações sensíveis, nenhuma informação secreta deve ser enviada ao github, tais como:

.npmrc, secrets, senhas, strings de conexão de prod e etc...

### Additional Notes

[ The quality of your code is the resume of your work ]

This Pull Request successfully Closes #TaskID

2023-09-13 21:35 UTC, Adson-Gomes-Oliveira requested changes

2023-09-13 21:35 UTC, Adson-Gomes-Oliveira commented on src/support/helpers/userSerializer.ts
> +    } else {
Esse else contempla google e facebook?

2023-09-13 21:35 UTC, Adson-Gomes-Oliveira commented on src/support/helpers/userSerializer.ts
> +export default function userSerializer(userProfile: any): User {
Seria interessante ver o retorno de cada provider, depois fazer uma tipagem com os retornos dos providers, algo como:
- GoogleAuthenticationReturn
- FacebookAuthenticationReturn
- DiscordAuthenticationReturn

E eles seriam a tipagemdo userProfile: `export default function userSerializer(userProfile: GoogleAuthenticationReturn | FacebookAuthenticationReturn | DiscordAuthenticationReturn): User {`

2023-09-13 21:35 UTC, Adson-Gomes-Oliveira commented on src/types/User.ts
> +export interface User {
Tanto o nome da interface quanto do arquivo dão a entender que a interface se trata da entidade de usuário, mas verdade ela se trata da entidade usuário serializada.

Então uma sugestão seria trocar o nome do arquivo para Serializer e da interface para UserSerialized, dentro do arquivo Serialized também ficariam os tipos:
- GoogleAuthenticationReturn
- FacebookAuthenticationReturn
- DiscordAuthenticationReturn

2023-09-13 21:35 UTC, Adson-Gomes-Oliveira commented on test/unit/support/mocks/user/userProfiles.ts
Já existe uma pasta para mocks, fica nesse caminho:
`src/support/mocks`

- [ ] Crie a pasta de user
- [ ] Crie dentro da pasta user um index.ts
- [ ] Crie dentro da pasta user um arquivo para guardar os mocks desde arquivo que você fez ( Um arquivo para cada provider )
- [ ] Faça export de cada um desses mocks e importe todos no arquivo index.ts
- [ ] Faça um export default no index.ts exportando os mocks com nomes unicos, ex:
![image](https://github.com/TableRise/tablerise-backend/assets/87550173/4780feb2-0084-4ad5-91c5-51a9fa979bca)

Agora é só utilizar os mocks a partir do arquivo index.ts de `src/support/mocks/user` onde precisar.

2023-09-14 16:53 UTC, RafaelCunhaS commented on src/support/helpers/userSerializer.ts
> +export default function userSerializer(userProfile: any): User {
Perfeito, utilizei a tipagem de cada provedor do próprio passport.

2023-09-14 16:55 UTC, RafaelCunhaS commented on src/types/User.ts
> +export interface User {
Boa, realmente 'User' apenas estava muito genérico.

2023-09-14 22:37 UTC, Adson-Gomes-Oliveira approved these changes

2023-09-16 23:05 UTC, merged