#162 - Create update email route
TableRise/tablerise-backend pull request #194
Opened 2023-10-13 16:06 UTC by RafaelCunhaS

### Technical Checklist

* [x] Garanti que todos os arquivos criados possuem testes unitários ( quando aplicável ).
* [x] Garanti que todos os fluxos criados possuem testes de integração.
* [x] Nenhuma mudança foi feita na estrutura de rotas, ou, se foi feita o arquivo do swagger foi atualizado.
* [x] A pipeline foi executada com sucesso e a cobertura de testes atingiu ou passou de 90%.
* [x] Ao finalizar a task movi meu card para a coluna de CodeReview e enviei o link da PR no discord para aprovação.

⚠️ Cuidado com os arquivos e informações sensíveis, nenhuma informação secreta deve ser enviada ao github, tais como:

.npmrc, secrets, senhas, strings de conexão de prod e etc...

### Additional Notes

[ The quality of your code is the resume of your work ]

This Pull Request successfully Closes #TaskID

2023-10-13 18:04 UTC, Adson-Gomes-Oliveira requested changes

2023-10-13 18:04 UTC, Adson-Gomes-Oliveira commented on src/routes/user/swagger.ts
> +        false,
O último argumento se refere a necessidade de autenticação para performar a operação, para um usuário atualizar um email ele precisar estar autenticado na plataforma, ou seja, true.

2023-10-13 18:04 UTC, Adson-Gomes-Oliveira commented on src/routes/user/userRoutes.ts
> +router.patch('/:id/update/email', controllers.updateEmail);
Rota deve ficar abaixo da linha 34 para que a autenticação seja obrigatória.

2023-10-13 18:04 UTC, Adson-Gomes-Oliveira commented on src/services/helpers/HttpRequestErrors.ts
> +            case 'invalid-code':
Sugestão: invalid-email-verify-code

2023-10-14 12:18 UTC, RafaelCunhaS commented on src/routes/user/swagger.ts
> +        false,
Boa, valeu!

2023-10-14 12:21 UTC, RafaelCunhaS commented on src/routes/user/userRoutes.ts
> +router.patch('/:id/update/email', controllers.updateEmail);
Beleza, nem me liguei na autenticação

2023-10-14 12:26 UTC, RafaelCunhaS commented on src/services/helpers/HttpRequestErrors.ts
> +            case 'invalid-code':
Perfeito, atualizado

2023-10-14 16:02 UTC, Adson-Gomes-Oliveira approved these changes

2023-10-14 17:57 UTC, merged