[ DEV-35 ] Create interfaces for spells and classes
TableRise/tablerise-backend pull request #27
Opened 2023-07-11 00:06 UTC by RasecMH

2023-07-11 00:25 UTC, ashtrindade approved these changes

2023-07-11 00:52 UTC, Adson-Gomes-Oliveira requested changes

2023-07-11 00:52 UTC, Adson-Gomes-Oliveira commented on src/schemas/spellsValidationSchema.ts
> +  higherLevels: higherLevelsZodSchema,
Uma coisa que esqueci de comentar durante a explicação foi que lá no diagrama do draw.io, todos os campos em que os tipos forem:

[ str ]
[ obj ] 
[ int ]

Isso quer dizer que aquele campo é um array do seu tipo, por exemplo, lá no diagrama higherLevels está como [ obj ] e no código está como apenas um objeto isolado, então o certo nessa linha 15 seria:

`higherLevels: z.array(higherLevelsZodSchema)`

2023-07-12 03:33 UTC, Adson-Gomes-Oliveira approved these changes

2023-07-12 17:24 UTC, merged