#267 - Refactor reset password route
TableRise/tablerise-backend pull request #271
Opened 2024-01-13 17:49 UTC by RasecMH

### Technical Checklist

* [ ] Garanti que todos os arquivos criados possuem testes unitários ( quando aplicável ).
* [ ] Garanti que todos os fluxos criados possuem testes de integração.
* [ ] Nenhuma mudança foi feita na estrutura de rotas, ou, se foi feita o arquivo do swagger foi atualizado.
* [ ] A pipeline foi executada com sucesso e a cobertura de testes atingiu ou passou de 90%.
* [ ] Ao finalizar a task movi meu card para a coluna de CodeReview e enviei o link da PR no discord para aprovação.

⚠️ Cuidado com os arquivos e informações sensíveis, nenhuma informação secreta deve ser enviada ao github, tais como:

.npmrc, secrets, senhas, strings de conexão de prod e etc...

### Additional Notes

[ The quality of your code is the resume of your work ]

This Pull Request successfully Closes #TaskID

2024-01-14 13:06 UTC, Adson-Gomes-Oliveira requested changes

2024-01-14 13:06 UTC, Adson-Gomes-Oliveira commented on src/domains/common/helpers/parametersWrapper.ts
> +export function generateEmailParam(): RouteDeclareParams[] {
O email já está sendo setado em outras rotas como query param então é interessante para seguir o padrão utilizar o método generateQueryParam para setar o email como parâmetro da rota.

![image](https://github.com/TableRise/tablerise-backend/assets/87550173/9523c1e6-080b-49a7-8ac6-e081805611a7)

2024-01-14 18:56 UTC, RasecMH commented on src/domains/common/helpers/parametersWrapper.ts
> +export function generateEmailParam(): RouteDeclareParams[] {
No caso eu troco o email de parâmetro para query ou só declaro como query mas mantenho como parâmetro?

2024-01-15 00:06 UTC, Adson-Gomes-Oliveira commented on src/domains/common/helpers/parametersWrapper.ts
> +export function generateEmailParam(): RouteDeclareParams[] {
Toca de param para query

2024-01-16 23:10 UTC, Adson-Gomes-Oliveira approved these changes

2024-01-16 23:10 UTC, merged