Feat/286/develop database type for characters
TableRise/tablerise-backend pull request #301
Opened 2024-02-26 19:10 UTC by junglejf

### Technical Checklist

* [x] Garanti que todos os arquivos criados possuem testes unitários ( quando aplicável ).
* [x] Garanti que todos os fluxos criados possuem testes de integração.
* [x] Nenhuma mudança foi feita na estrutura de rotas, ou, se foi feita o arquivo do swagger foi atualizado.
* [x] A pipeline foi executada com sucesso e a cobertura de testes atingiu ou passou de 90%.
* [x] Ao finalizar a task movi meu card para a coluna de CodeReview e enviei o link da PR no discord para aprovação.

⚠️ Cuidado com os arquivos e informações sensíveis, nenhuma informação secreta deve ser enviada ao github, tais como:

.npmrc, secrets, senhas, strings de conexão de prod e etc...

### Additional Notes

[ The quality of your code is the resume of your work ]

This Pull Request successfully Closes #TaskID

2024-02-26 19:31 UTC, Adson-Gomes-Oliveira requested changes

2024-02-26 19:31 UTC, Adson-Gomes-Oliveira commented on src/types/models/characters/charactersDnd5e.d.ts
Essas definiçoes devem estar dentro da nossa lib database-management, só cortar daqui colar lá no arquivo correto ( seguir o path que já existe na lib ), criar uma PR e me mandar.

Link da nossa lib database-management:

https://github.com/TableRise/database-management

- Remover esse arquivo do projeto principal.

2024-02-26 20:37 UTC, junglejf commented on src/types/models/characters/charactersDnd5e.d.ts
feito 

https://github.com/TableRise/database-management/pull/3

2024-02-27 06:45 UTC, Adson-Gomes-Oliveira approved these changes

2024-02-27 06:46 UTC, merged