#309 - Create route to recover all campaings
TableRise/tablerise-backend pull request #323
Opened 2024-04-12 19:19 UTC by junglejf

### Technical Checklist

* [ ] Garanti que todos os arquivos criados possuem testes unitários ( quando aplicável ).
* [ ] Garanti que todos os fluxos criados possuem testes de integração.
* [ ] Nenhuma mudança foi feita na estrutura de rotas, ou, se foi feita o arquivo do swagger foi atualizado.
* [ ] A pipeline foi executada com sucesso e a cobertura de testes atingiu ou passou de 90%.
* [ ] Ao finalizar a task movi meu card para a coluna de CodeReview e enviei o link da PR no discord para aprovação.

⚠️ Cuidado com os arquivos e informações sensíveis, nenhuma informação secreta deve ser enviada ao github, tais como:

.npmrc, secrets, senhas, strings de conexão de prod e etc...

### Additional Notes

[ The quality of your code is the resume of your work ]

This Pull Request successfully Closes #TaskID

2024-04-13 13:43 UTC, ashtrindade requested changes
Aguardando ajustes.

2024-04-13 13:43 UTC, ashtrindade commented on .vscode/settings.json
> +{
Acredito que esse arquivo não seja necessário.

2024-04-13 13:43 UTC, ashtrindade commented on src/types/modules/core/campaigns/CampaignsDependencies.d.ts
> +    // operations
Esse comentário é necessário?

2024-04-13 13:43 UTC, ashtrindade commented on src/types/modules/core/campaigns/CampaignsDependencies.d.ts
> +    // services
Esse comentário é necessário?

2024-04-13 13:43 UTC, ashtrindade commented on tests/unit/interface/campaigns/presentation/campaigns/CampaignsRoutes.spec.ts
> +            expect(routes).to.have.lengthOf(filesLength);
Esse tipo de asserção não viola o propósito do teste? Ter uma asserção estática garante que qualquer alteração indevida seja detectada nos testes.

2024-04-13 13:43 UTC, ashtrindade commented on tests/unit/interface/campaigns/presentation/campaigns/RoutesDescription.spec.ts
> +            expect(descLength).to.be.equal(filesLength);
Mesma questão do comentário anterior, sugiro ter um número fixo do _length_ esperado.

2024-04-14 04:39 UTC, Adson-Gomes-Oliveira commented on tests/unit/interface/campaigns/presentation/campaigns/CampaignsRoutes.spec.ts
> +const filesLength = readdirSync(path).length;
Podem existir rotas que não necessariamente possuem um service, hoje não existem, mas pelo conceito podem existir.

2024-04-16 18:55 UTC, ashtrindade approved these changes

2024-04-17 01:26 UTC, merged