#86a3g57v3 - Add size to races schema
TableRise/tablerise-backend pull request #338
Opened 2024-05-27 20:13 UTC by RasecMH

### Technical Checklist

* [ ] Garanti que todos os arquivos criados possuem testes unitários ( quando aplicável ).
* [ ] Garanti que todos os fluxos criados possuem testes de integração.
* [ ] Nenhuma mudança foi feita na estrutura de rotas, ou, se foi feita o arquivo do swagger foi atualizado.
* [ ] A pipeline foi executada com sucesso e a cobertura de testes atingiu ou passou de 90%.
* [ ] Ao finalizar a task movi meu card para a coluna de CodeReview e enviei o link da PR no discord para aprovação.

⚠️ Cuidado com os arquivos e informações sensíveis, nenhuma informação secreta deve ser enviada ao github, tais como:

.npmrc, secrets, senhas, strings de conexão de prod e etc...

### Additional Notes

[ The quality of your code is the resume of your work ]

This Pull Request successfully Closes #TaskID

2024-05-27 20:13 UTC, Adson-Gomes-Oliveira commented
Task linked: [CU-86a3g57v3 Adicionar nova propriedade a entidade de raças D&D](https://app.clickup.com/t/86a3g57v3)

2024-05-27 20:55 UTC, ashtrindade approved these changes

2024-05-27 21:01 UTC, Adson-Gomes-Oliveira requested changes

2024-05-27 21:01 UTC, Adson-Gomes-Oliveira commented on src/infra/datafakers/dungeons&dragons5e/generators/generateDungeonsAndDragonsFaker.ts
> +            size: '1,85m',
Essa prop se refere aos seguintes valores:

tiny, small, medium, huge, large e gargantuam não necessariamente a medida de altura.

2024-05-27 21:01 UTC, Adson-Gomes-Oliveira commented on src/infra/data/dungeons&dragons5e/racesSeeder.json
> +            "size": "1,85m",
Por enquanto não é necessária essa informação no seeder, será adicionada em um momento futuro.

2024-05-29 15:04 UTC, Adson-Gomes-Oliveira approved these changes

2024-05-29 15:04 UTC, merged