#86a3bv7z7 - Create update images from campaign route
TableRise/tablerise-backend pull request #347
Opened 2024-06-10 00:02 UTC by RafaelCunhaS

### Technical Checklist

* [ ] Garanti que todos os arquivos criados possuem testes unitários ( quando aplicável ).
* [ ] Garanti que todos os fluxos criados possuem testes de integração.
* [ ] Nenhuma mudança foi feita na estrutura de rotas, ou, se foi feita o arquivo do swagger foi atualizado.
* [ ] A pipeline foi executada com sucesso e a cobertura de testes atingiu ou passou de 90%.
* [ ] Ao finalizar a task movi meu card para a coluna de CodeReview e enviei o link da PR no discord para aprovação.

⚠️ Cuidado com os arquivos e informações sensíveis, nenhuma informação secreta deve ser enviada ao github, tais como:

.npmrc, secrets, senhas, strings de conexão de prod e etc...

### Additional Notes

[ The quality of your code is the resume of your work ]

This Pull Request successfully Closes #TaskID

2024-06-10 00:02 UTC, Adson-Gomes-Oliveira commented
Task linked: [CU-86a3bv7z7 Criar rota para atualizar imagens gerais de uma campanha](https://app.clickup.com/t/86a3bv7z7)

2024-06-10 02:50 UTC, Adson-Gomes-Oliveira requested changes
Code coverage em statements não bateu os 100%, provavelmente deve ser algum detalhe de alguma linha que faltou testar. Sugiro utilizar o html gerado pelo npm run coverage para validar.

2024-06-10 02:50 UTC, Adson-Gomes-Oliveira commented on src/core/campaigns/services/UpdateCampaignImagesService.ts
> +        if (operation === 'add' && imageUploadResponse) {
Como esse if tem uma complexidade maior ( if dentro de if com else ) para uma leitura melhor do código ( clean code ), é mais interessante que cada if desse seja um método, exemplo: **addCampaignImage** e **removeCampaignImage** que vão abstrair a lógica dos ifs para os métodos deixando o método principal mais clean.

2024-06-10 02:50 UTC, Adson-Gomes-Oliveira commented on src/core/campaigns/services/UpdateCampaignImagesService.ts
> +        if (operation === 'remove' && campaign.images) {
Mesmo ponto citado acima.

2024-06-15 21:02 UTC, RafaelCunhaS commented on src/core/campaigns/services/UpdateCampaignImagesService.ts
> +        if (operation === 'add' && imageUploadResponse) {
Boa! Alterado.

2024-06-15 23:31 UTC, Adson-Gomes-Oliveira approved these changes

2024-06-15 23:32 UTC, merged