#TR-84 - Redirect after social login
TableRise/tablerise-backend pull request #391
Opened 2024-10-04 01:37 UTC by RasecMH

### Technical Checklist

* [ ] Garanti que todos os arquivos criados possuem testes unitários ( quando aplicável ).
* [ ] Garanti que todos os fluxos criados possuem testes de integração.
* [ ] Nenhuma mudança foi feita na estrutura de rotas, ou, se foi feita o arquivo do swagger foi atualizado.
* [ ] A pipeline foi executada com sucesso e a cobertura de testes atingiu ou passou de 90%.
* [ ] Ao finalizar a task movi meu card para a coluna de CodeReview e enviei o link da PR no discord para aprovação.

⚠️ Cuidado com os arquivos e informações sensíveis, nenhuma informação secreta deve ser enviada ao github, tais como:

.npmrc, secrets, senhas, strings de conexão de prod e etc...

### Additional Notes

[ The quality of your code is the resume of your work ]

This Pull Request successfully Closes #TaskID

2024-10-04 03:52 UTC, Adson-Gomes-Oliveira commented
Atualizar lib express
https://github.com/TableRise/tablerise-backend/security/dependabot/13

2024-10-09 18:16 UTC, Adson-Gomes-Oliveira requested changes

2024-10-09 18:16 UTC, Adson-Gomes-Oliveira commented on src/interface/users/presentation/oauth/OAuthRoutes.ts
> +                            passReqToCallback: true,
Qual o objetivo destas opções e porque elas se aplicam aqui mas não no contexto do google?

2024-10-09 18:17 UTC, Adson-Gomes-Oliveira commented
Aplicar os comentários de seguranças feitos pelo github acima.

2024-10-09 21:24 UTC, RasecMH commented on src/interface/users/presentation/oauth/OAuthRoutes.ts
> +                            passReqToCallback: true,
Aparentemente essa lib do discord não é mantida a 4 anos e por algum motivo ela não repassa o request/mantém a sessão quando chama a callback.

2024-10-10 03:56 UTC, Adson-Gomes-Oliveira commented on src/interface/users/presentation/oauth/OAuthRoutes.ts
> +                            passReqToCallback: true,
Ok, entendido.

2024-10-26 22:59 UTC, Adson-Gomes-Oliveira approved these changes

2024-10-26 22:59 UTC, merged