#TR-89 - Adjust seeders ded5 races ability score field
TableRise/tablerise-backend pull request #393
Opened 2024-10-05 12:30 UTC by junglejf

### Technical Checklist

* [ ] Garanti que todos os arquivos criados possuem testes unitários ( quando aplicável ).
* [ ] Garanti que todos os fluxos criados possuem testes de integração.
* [ ] Nenhuma mudança foi feita na estrutura de rotas, ou, se foi feita o arquivo do swagger foi atualizado.
* [ ] A pipeline foi executada com sucesso e a cobertura de testes atingiu ou passou de 90%.
* [ ] Ao finalizar a task movi meu card para a coluna de CodeReview e enviei o link da PR no discord para aprovação.

Obs.:
- As libs já foram corrigidas aprovadas e agora os campos _id desnecessários foram removidos.
- A lib populate não está mais quebrando com o raceSeeders
- Nessa PR teve atualizaçao da Db-seeders versão 5.3.3 e Bd-Management 5.0.1: links abaixo

https://github.com/TableRise/database-seeder/pull/12
https://github.com/TableRise/database-management/pull/24

⚠️ Cuidado com os arquivos e informações sensíveis, nenhuma informação secreta deve ser enviada ao github, tais como:

.npmrc, secrets, senhas, strings de conexão de prod e etc...

### Additional Notes

[ The quality of your code is the resume of your work ]

This Pull Request successfully Closes #TaskID

2024-10-05 20:36 UTC, Adson-Gomes-Oliveira requested changes

2024-10-05 20:36 UTC, Adson-Gomes-Oliveira commented on src/infra/data/dungeons&dragons5e/racesSeeder.json
> -    {
A raça Half-Elf não deve ser removida

2024-10-05 22:01 UTC, junglejf commented on src/infra/data/dungeons&dragons5e/racesSeeder.json
> -    {
corrigi e devolvi

2024-10-06 06:09 UTC, Adson-Gomes-Oliveira approved these changes

2024-10-06 06:09 UTC, merged