#TR-88 - Create ban endpoint
TableRise/tablerise-backend pull request #398
Opened 2024-12-10 23:57 UTC by isaciqo

### Technical Checklist

* [x] Garanti que todos os arquivos criados possuem testes unitários ( quando aplicável ).
* [x] Garanti que todos os fluxos criados possuem testes de integração.
* [x] Nenhuma mudança foi feita na estrutura de rotas, ou, se foi feita o arquivo do swagger foi atualizado.
* [x] A pipeline foi executada com sucesso e a cobertura de testes atingiu ou passou de 90%.
* [x] Ao finalizar a task movi meu card para a coluna de CodeReview e enviei o link da PR no discord para aprovação.

⚠️ Cuidado com os arquivos e informações sensíveis, nenhuma informação secreta deve ser enviada ao github, tais como:

.npmrc, secrets, senhas, strings de conexão de prod e etc...

### Additional Notes

[ The quality of your code is the resume of your work ]

This Pull Request successfully Closes #TaskID

2024-12-13 13:03 UTC, Adson-Gomes-Oliveira requested changes

2024-12-13 13:03 UTC, Adson-Gomes-Oliveira commented on src/core/campaigns/services/PostBanPlayerService.ts
> +    }
O Projeto tem objetivo de seguir os conceitos de SOLID já que estamos utilizando o TypeScript, um desses conceitos é o próprio S da sigla, Single Responsability Principle, onde devemos tentar sempre atribuir uma unica funcionalidade a um método, como existem 2 operações de update nessa função, seria interessante que elas estivessem em um método de save separado, caso fosse apenas 1 operação não veria necessidade (debatível).

2024-12-13 13:03 UTC, Adson-Gomes-Oliveira commented on src/interface/campaigns/presentation/campaigns/CampaignsController.ts
> +        return res.status(HttpStatusCode.OK).end();
O código para resposta sem retorno é 204 = NO_CONTENT

2024-12-13 13:03 UTC, Adson-Gomes-Oliveira commented on src/interface/campaigns/presentation/campaigns/CampaignsRoutes.ts
> +                    tag: 'ban',
Essa tag indica a categoria da rota no swagger, faz sentido existir uma categoria "ban" só pra essa rota?

2024-12-13 13:03 UTC, Adson-Gomes-Oliveira commented on src/interface/campaigns/presentation/campaigns/RoutesDescription.ts
> +const banPlayer = 'This route banish a players';
player * ✌️  kkk

2024-12-15 07:12 UTC, Adson-Gomes-Oliveira commented on src/interface/campaigns/presentation/campaigns/CampaignsRoutes.ts
> +                    tag: 'ban',
Mas será que o melhor nome rpa categoria é ban?

2024-12-15 07:20 UTC, Adson-Gomes-Oliveira commented on src/core/campaigns/services/PostBanPlayerService.ts
> +    }
A intenção da operation é ser um orquestrador dos métodos da service, a service é uma caixa de ferramentas, a operation é o operador, por sua vez ele utilizará cada ferramenta que a service oferece (métodos) para cumprir seu objetivo.

A necessidade da separação surge a partir do contexto que é diferente:

> Princípio da Responsabilidade Única — Uma classe deve ter um, e somente um, motivo para mudar.
Esse princípio declara que uma classe deve ser especializada em um único assunto e possuir apenas uma responsabilidade dentro do software, ou seja, a classe deve ter uma única tarefa ou ação para executar.
[Principios do SOLID](https://medium.com/desenvolvendo-com-paixao/o-que-é-solid-o-guia-completo-para-você-entender-os-5-princípios-da-poo-2b937b3fc530)

Um método para o processamento das informações;
Um método para o salvamento das informações já processadas;

É possível processar sem salvar, assim como é possível salvar sem processar, logo são dois métodos, com dois objetivos distintos que se complementam e geram um fluxo.

2024-12-16 20:22 UTC, isaciqo commented on src/core/campaigns/services/PostBanPlayerService.ts
> +    }
blz, tá ajustado já

2024-12-16 20:23 UTC, isaciqo commented on src/interface/campaigns/presentation/campaigns/CampaignsRoutes.ts
> +                    tag: 'ban',
Acha valido reabrir a PR pra colocar um "ban player", sendo que está dentro do contexto campanha?

2024-12-22 00:37 UTC, Adson-Gomes-Oliveira commented on src/interface/campaigns/presentation/campaigns/CampaignsRoutes.ts
> +                    tag: 'ban',
A PR não está fechada, tem alguns conflitos para resolver, dá pra fazer aqui pelo github mesmo.

A ideia das tags é agruparem no swagger um grupo de rotas que fazem parte de um mesmo contexto, só existe 1 rota para banimento de player não faz sentido existir 1 tag para só 1 rota. Já existe uma tag a qual se encaixaria essa rota: **management**

2025-01-23 12:30 UTC, merged